language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email:
    recipients:
      - secure: "oragnT/ylb5mUG+qyuLYIc/dE5RWQUl5+S292i0YNj+wqq+4OpQ6NVf4nGRyg52S87y5NiBmNbsVf2z+M5rKYhM06mA/PjhFYb0uL3ki4vzMzijszWV/TAZ3+lF21KquZ9puOS6Q5GSzJ5OHg0q3APbp/6Uq7N3FcOpnMbGHjPJQYYUi0M7B2l9x/VRF3Qjk4oNsMKYbYnUstHVQcu9M6yXVxxKMzcBQfXAdERX6Qcl/kprZi9j5LfttD5h8BdKfqy637+3hXFjUHlLZ4GTzWYRd7ilQUKVa4AwZsJTDTrYdSI97spfSEDTQW2jEPwB2s8dQwmx9rO+T23KFLQqZ+wMhJzDarF/GK9cLl96vN95qaLf7gZrWeiSHCQkdoDEhrLPhzpHT5GBtRfG5pqW5uXcMjeeYRiy3jl2If+NAT6x4KEZCamNXB3B0mUW3PWfiB20eq6ssly2J/JOqDN+Wa8/ew3MZu2kD396o8utSLxT3c4xVV/DBuhnHNZSOVcK/G110WnpupMZaMo92A/oO0oY7WZ6zxmtr1WiCizpLmhKyMp41/WTLTt2wEBRibBhvKAXWY4ozvqRdGvVktDruI2y5VVMPIfUYZOLDop2dJDxyshMsyFNiuQ62Ds/Zxn9sb3WQ4Yd4dOGXgYFWwRDFBE+EoO7iRQ58yt7k5C1kfHI="
      - secure: "mdgMU7cEvUEVaQODAhsGzBMU4F/QMEytv8k8vHiLrRNvcWt3RZ+I49bHWdWLmS5tM96mwUmLKwNlvec6Tb8q4P8aguTZfKYWvE2yZKVT2nL4TjGrLViegbbsF+ckfKNEfqBpEC4Bj3Pj9IF56TSbG8kOxCZXBMitoAMWZ4bsb4iNUZZs1SUcH9nIuTC8JecylXY/IFDa11IxMbV2/wgWnEYQzUGiZrMqGQKAf0/ELEgDQz+iud9gKj6i/3mLEoJz5D3WkJUuLjcxSx+TZvbjAEeBf8z4gnhQvv0VVCWX5DfGvQQj9OWN9qudwkRFLpopG26MJ15RjQD82z32ICKQZEF4nUsTV3ngyfwup3Yo/x+WpfYPunlZAAls/z/q5fkbNsZt2OJXMX4Ce1BYaM4jUNMx6ynBX8Sa2+kqgS56tIkRmAxSaIq1BkLUwKoLhoS7N2W4z/V2ANeKfpARLurF6lUP5zMdQg6pwEWTe17WMBsPQNnrB4mXAL0ztwund7kYKrvQejGRpvtlEvvvl6Y4io7eb1w1L2k11niWKx2n3VYoG+m04ZQ1p2zZ82eX1E19jM9vp33rqjhhI0U0TwlnXBbHuIoDAFCqSb1jKnnILesGctiaJtF086qIHtfkDyZ+PKRebAOM+mgk3HdhWBdPOwx2qYDnqaLKxOZ/cI31+5k="
    on_success: never
    on_failure: never

sudo: false

addons:
  apt:
    packages:
      - parallel

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Enables us to test dev-master
  - composer config minimum-stability dev
  - composer config prefer-stable true
  # Installs TYPO3
  - travis_wait 30 composer require --dev nimut/typo3-complete=$TYPO3_VERSION
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  #- composer require typo3/cms-core=$TYPO3_VERSION
  # Locating UnitTests.xml
  - export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'
  # Location FunctionalTests.xml
  - export "FUNCTIONAL_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml'
  - ln -nfs .Build/vendor/typo3/cms/typo3 typo3

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      .Build/bin/phpunit --whitelist Classes/ --coverage-clover=functional-coverage.clover --colors -c $FUNCTIONAL_XML Tests/Functional
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      php ocular.phar code-coverage:upload --format=php-clover functional-coverage.clover
    fi
  - >
    echo;
      echo "Running php lint";
      find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" ! -path "./typo3_src/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

jobs:
  allow_failures:
    - env: TYPO3_VERSION=^10.1 COVERAGE=0 FUNCTIONAL=0
    - env: TYPO3_VERSION=^10.1 COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
  include:
    - stage: test
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - stage: test
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=1
      php: 7.0
    - stage: test
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - stage: test
      env: TYPO3_VERSION=^8.7 COVERAGE=1 FUNCTIONAL=1
      php: 7.2
    - stage: test
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 7.3
    - stage: test
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=1
      php: 7.2
    - stage: test
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
      php: 7.3
    - stage: test
      env: TYPO3_VERSION=^10.1 COVERAGE=0 FUNCTIONAL=1
      php: 7.2
    - stage: test
      env: TYPO3_VERSION=^10.1 COVERAGE=0 FUNCTIONAL=0
      php: 7.3

    - stage: ship to ter
      if: tag IS present
      php: 7.0
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client
            # Build extension files
            composer extension-release
            # Upload
            TAG_MESSAGE=`git log -1 --pretty=%B`
            echo "Tag-Message: ${TAG_MESSAGE}"
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload aoe_dbsequenzer . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
