<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-04-17 14:15

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('aoe_dbsequenzer');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_aoedbsequenzer_basetest' => $extensionPath . 'Tests/BaseTest.php',
	'tx_aoedbsequenzer_domain_model_overwriteprotection' => $extensionClassesPath . 'Domain/Model/Overwriteprotection.php',
	'tx_aoedbsequenzer_domain_repository_overwriteprotectionrepository' => $extensionClassesPath . 'Domain/Repository/OverwriteprotectionRepository.php',
	'tx_aoedbsequenzer_overwriteprotectionservice' => $extensionClassesPath . 'OverwriteProtectionService.php',
	'tx_aoedbsequenzer_overwriteprotectionservicetest' => $extensionPath . 'Tests/OverwriteProtectionServiceTest.php',
	'tx_aoedbsequenzer_sequenzer' => $extensionClassesPath . 'Sequenzer.php',
	'tx_aoedbsequenzer_typo3service' => $extensionClassesPath . 'TYPO3Service.php',
	'tx_aoedbsequenzer_typo3servicetest' => $extensionPath . 'Tests/TYPO3ServiceTest.php',
    'tx_aoedbsequenzer_form_overwritetillelement' => $extensionPath . 'Form/Tx_AoeDbsequenzer_Form_OverwriteTillElement.php',
    'tx_aoedbsequenzer_form_overwritemodeelement' => $extensionPath . 'Form/Tx_AoeDbsequenzer_Form_OverwriteModeElement.php',
);
